### ISSUE TITLE
mod.ts missing ArrayBuffer handling

### ISSUE THREAD

**Issue by nhrones** [MierenManz/v8_format#6]
mod.ts is missing ArrayBuffer handling

```ts
// insert at line-2
import { deserializeArrayBuffer, serializeArrayBuffer } from "./array_buffer.ts";

// insert at line-29 below `case "object": {`
      if (value.constructor.name === 'ArrayBuffer') {
        return serializeArrayBuffer(value)
      }

// insert at line-81 below `case 0x5E:
      // ArrayBuffer
      case 0x42:
         return deserializeArrayBuffer(data);
```

**Comment by nhrones** [comment]
I've been using a local copy for testing, and so far this is all I'd need to link directly to your repo.
I've done extensive testing, and so far no other issues.

Thanks for this! It looks like you've put a lot of effort on this.

**Comment by MierenManz** [comment]
If possible I'd like to use instanceof to detect array buffers but this seems like a good idea
