### ISSUE TITLE
Consume magic

### ISSUE THREAD

**Issue by nhrones** [MierenManz/v8_format#7]
I'll be deserializing raw values from DenoKv SQLite records.  I can eliminate a function call if the deserializeAny() function in mod.ts would automatically handle consuming the V8 magic bytes. 

In mod.ts
```ts
import { consume, isSMI } from "./_util.ts";

// in function deserializeAny
export function deserializeAny(data: Uint8Array, objRefs: {}[] = []): any {
   // if exists v8 magic, consume it
   if (data[0] === 0xff && data[1] === 0x0f) consume(data, 2);
```  
Serialize is not an issue.  This is easy for me to auto-add on DB-Set.
If you'd prefer to not make these changes, I could just fork this repo.
Let me know what you think, and thanks again.

Looks like Verstappen may have some real competition tomorrow!

**Comment by MierenManz** [comment]
This change seems like a good idea. Feel free to pr
